### ISSUE TITLE
去学学git工具吧，在家里可以实时更新，极其方便

### ISSUE THREAD

**Issue by ice1000** [EternalAddiCtion/oi-codes#1]
如题 :joy: 
同时推荐你去学习markdown语法，看看下面这个：
+ 一个点
+ 两个点

# 大号字
[链接：Emacs](https://www.zhihu.com/question/20846396 "这可是神器，好好看着！")<br/>
表格：<br/>

Android|Java|C
:---:|:---:|:---:
[AIAndroid](https://github.com/ice1000/AIAndroid "我称之为人工少女")|[城堡游戏](https://github.com/ice1000/Castle-game "使用Java swing实现")|[树莓派小车程序](https://github.com/ice1000/car-on-RPi "毫无技术含量")
[鬼畜机](https://github.com/ice1000/GhostAnimalPlayer "手机上弹奏属于你的鬼畜")|null|null

**Comment by EternalAddiCtion** [comment]
imma gonna use vim.i gotta say that Fuck you ,silly b!

**Comment by ice1000** [comment]
:facepunch: F@CK U leather man :facepunch:
